apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  containers:
  - name: branching-strategy
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    ports:
    - containerPort: {{ .Values.containerPort }}
    env:
    - name: ENV_NAME
      value: {{ .Values.envName | quote }}
