namespace: dev

image:
  repository: 590183687498.dkr.ecr.ap-south-1.amazonaws.com/api-staging
  tag: main-11575316581

containerPort: 5000 

envName: dev

service:
  type: ClusterIP
  port: 80  
  targetPort: 5000

ingress:
  host: "dev-branching.shariff.info"
  path: "/"
