namespace: prod

image:
  repository: navabnaeem/branching-strategy
  tag: v1

containerPort: 5000 
envName: prod

service:
  type: ClusterIP
  port: 80 
  targetPort: 5000

ingress:
  host: "prod-branching.shariff.info"
  path: "/"
