name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read  

env:
  AWS_REGION : "ap-south-1"
  # DB_HOST: ${{ secrets.DB_HOST }}
  # DB_USER: ${{ secrets.DB_USER }}
  # DB_PASS: ${{ secrets.DB_PASS }}
  # DB_NAME: ${{ secrets.DB_NAME }}
  # DB_PORT: ${{ secrets.DB_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::590183687498:role/github-role
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}


    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=min
        tags: ${{ steps.login-ecr.outputs.registry }}/api-staging:${{ github.ref_name }}-${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the deploy job runs after the build job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.8.0'

    - name: Deploy to Kubernetes using Helm
      env:
        IMAGE_TAG: ${{ github.ref_name }}-${{ github.run_id }}
      run: |
        cd helm
        helm upgrade "branching-strategy" --install . \
          -f env/dev.yaml --namespace dev --create-namespace \
          --set image.tag="$IMAGE_TAG"